#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE holder;
    CREATE DATABASE account;
    GRANT ALL PRIVILEGES ON DATABASE holder TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE account TO $POSTGRES_USER;
EOSQL