server:
  port: 8081

spring:
  application:
    name: holder

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/holder
    username: ${DB_USER:digital}
    password: ${DB_PASSWORD:digital}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /holder/swagger-ui.html
  api-docs:
    path: /holder/api-docs

aws:
  salt:
    secretId: ${AWS_SALT_SECRET_ID}


